package com.config;

import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import model.Message;

@RestController
@CrossOrigin
@RequestMapping("api/Setup/Config")
public class ConfigRestController {

@GetMapping
public Object index() {
    Message msg = new Message();
    String sql = "INSERT INTO user_type_master (id, designation, hierarchy) VALUES ('D', 'Designer', 1);\n"
              + "INSERT INTO user_type_master (id, designation, hierarchy) VALUES ('AD', 'Amin', 1);\n"
              + "INSERT INTO user_type_master (id, designation, hierarchy)  VALUES ('R', 'Rajasow', 1);\n"
              + "INSERT INTO user_type_master (id, designation, hierarchy)  VALUES ('B', 'Sub Engineer', 2);\n"
              + "INSERT INTO user_type_master (id, designation, hierarchy)  VALUES ('A', 'Engineer', 3);\n"
              + "INSERT INTO user_type_master (id, designation, hierarchy)  VALUES ('C', 'Chief', 4);";
    msg.db.save(sql);
    sql = "INSERT INTO organization_master (id, address, email, mayor_contat_no, mayor_name, \"name\", office_contact_no, office_name, secretary_contat_no, secretary_name, sub_mayor_contat_no, sub_mayor_name, url, phase1d, phase1a, phase1b, phase1c, phase2a, phase2b, phase2c, phase2d, phase3a, phase3b, phase3c, phase3d) VALUES (1, 'लहान, सिरहा, प्रदेश २, नेपाल', 'Organization Email', 'Organization Mayor Contact No', 'Organization Mayor Name', 'लहान नगरपालिका ', 'Organization Office Contact No', 'नगर कार्यपालिकाको कार्यालय', 'Organization Secretary Contact No', 'Organization Secretary Name', 'Organization Sub Mayor Contact No', 'Organization Sub Mayor Name', 'Organization URL', 6.1, 9.0, 9.0, 9.0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);";
    msg.db.save(sql);
    sql = "INSERT INTO organization_user (login_id, address, db_password, education_qualification, email, id, join_date, license_no, mobile, municipal_reg_no, photo, signature, stamp, status, token, user_name, user_type) VALUES ('ADMIN', NULL, 'EBPSADMIN', NULL, 'ADMIN', 1, '2019-08-08', NULL, '', NULL, NULL, NULL, NULL, 'Y', 'eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJBRE1JTiIsImF1ZCI6IkFETUlOIiwiaXNzIjoiQyIsInJvbGVzIjoidXNlciIsImlhdCI6MTU2NTg0Mzg0OSwiZXhwIjoxNTY1OTMwMjQ5fQ.jrHU4SWuKvuzpuHEtSpCsZe5I3baYClIW2PSX0jKx98', 'ADMIN', 'C');";
    msg.db.save(sql);

    sql = "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.1', 'Min. tread width of staircase', '1', 'Staircase', 'mm excluding nosing');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.2', 'Riser height of staircase', '1', 'Staircase', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.3', 'Clear width of staircase for', '1', 'Staircase', '');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.301', 'Hospital', '1', 'Staircase', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.302', 'Auditorium', '1', 'Staircase', '');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.30201', 'below 500 capacity', '1', 'Staircase', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.30202', 'above 500 capacity', '1', 'Staircase', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.303', 'Others', '1', 'Staircase', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.4', 'Height of handrial', '1', 'Staircase', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.5', 'Max. no of riser in one Single flight', '1', 'Staircase', 'Nos.');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.6', 'Max. head room under staircase from the nosing of the tread', '1', 'Staircase', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('2.1', 'Max. travel distance to exit point in each floor', '2', 'Exit', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('2.2', 'Min. width of exit door including frame', '2', 'Exit', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('2.3', 'Min. height of exit door including frame', '2', 'Exit', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('2.4', 'Shutter opening of exit door to staircase & public passage', '2', 'Exit', '');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('2.5', 'Total width of exit door', '2', 'Exit', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('3.1', 'Min. opening area of window for lighting largest habitable room from external wall', '3', 'Light and Ventilation', 'sq.m.');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('3.2', 'Min. opening area of natural ventilator for largest habitation room from external wall', '3', 'Light and Ventilation', 'sq.m.');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('3.3', 'Min. size of ventilator for water closets and bathroom', '3', 'Light and Ventilation', 'sq.m.');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('4.1', 'Total height of building', '4', 'Lifts', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('4.2', 'Provision for lift', '4', 'Lifts', '');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('4.3', 'No. of lift per bank', '4', 'Lifts', 'Nos.');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('5.1', 'Is there a provision of separate entrance for disabled people next to the primary entrance of a building', '5', 'Requirements for the physically disabled', '');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('5.2', 'Max. gradient for wheen chair ramp at entrance of building', '5', 'Requirements for the physically disabled', '');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('5.3', 'Min. width of wheel chair ramp at entrance of building', '5', 'Requirements for the physically disabled', 'mm');\n"
              + "INSERT INTO architectural_design_b_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('6.1', 'The height of parafet wall & balcony handrill', '6', 'Parapet heights', 'mm');";
    msg.db.save(sql);

    sql = "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.1', 'Min. tread width of staircase', '1', 'Staircase', 'mm excluding nosing');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.2', 'Riser height of staircase', '1', 'Staircase', 'mm');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.3', 'Clear width of staircase', '1', 'Staircase', 'mm');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.4', 'Height of handrial', '1', 'Staircase', 'mm');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.5', 'Max. no of riser in one Single flight', '1', 'Staircase', 'Nos.');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('1.6', 'Max. head room under staircase from the nosing of the tread', '1', 'Staircase', 'mm');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('2.1', 'Max. travel distance to exit point in each floor', '2', 'Exit', 'mm');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('2.2', 'Min. width of exit door including frame', '2', 'Exit', 'mm');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('2.3', 'Min. height of exit door including frame', '2', 'Exit', 'mm');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('2.4', 'Total width of exit door', '2', 'Exit', 'mm');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('3.1', 'Min. opening area of window for lighting largest habitable room from external wall', '3', 'Light and Ventilation', 'sq.m.');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('3.2', 'Min. opening area of natural ventilator for largest habitation room from external wall', '3', 'Light and Ventilation', 'sq.m.');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('3.3', 'Min. size of ventilator for water closets and bathroom', '3', 'Light and Ventilation', 'sq.m.');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('4.1', 'Is there a provision of separate entrance for disabled people next to the primary entrance of a building', '4', 'Requirements for the physically disabled', '');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('4.2', 'Max. gradient for wheen chair ramp at entrance of building', '4', 'Requirements for the physically disabled', '');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('4.3', 'Min. width of wheel chair ramp at entrance of building', '4', 'Requirements for the physically disabled', 'mm');\n"
              + "INSERT INTO architectural_design_c_master (id, building_elements, group_id, group_name, unit) "
              + "	VALUES ('5.1', 'The height of parafet wall & balcony handrill', '5', 'Parapet heights', 'mm');";
    msg.db.save(sql);

    sql = "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('1', 'Rating and size', '', '');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('1.1', 'Rating and size', 'sq.mm.', 'Minimum size (sq.mm) of copper cable for light circuit');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('1.2', 'Rating and size', 'sq.mm.', 'Minimum size (sq.mm) of copper cable for power circuit');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('1.3', 'Rating and size', 'watt', 'Wattage of ordinary power socket (2 pin) estimated as');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('1.4', 'Rating and size', 'watt', 'Wattage of ordinary power socket (3 pin) estimated as');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('1.5', 'Rating and size', 'mm.', 'Wall thickness of cast iron switch or regulator boxes');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('1.6', 'Rating and size', 'mm.', 'Wall thickness of mild steel sheet switch or regulator boxes for upto 20cm.x30cm.');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('1.7', 'Rating and size', 'mm.', '	Wall thickness of mild steel sheet switch or regulator boxes for upto 20cm.x30cm.');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('1.8', 'Rating and size', 'mm.', 'Depth of the switch or regulator boxes');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('2.', 'Maximum number of Cables in a Condut', '', '');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('2.1', 'Maximum number of Cables in a Condut', 'Nos. of cables', 'No. of 2.5 sq.mm. cross-sectional area cable in 20 mm. dia');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('2.2', 'Maximum number of Cables in a Condut', 'Nos. of cables', 'No. of 4 sq.mm. cross-sectional area cable in 20 mm. dia conduit');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('2.3', 'Maximum number of Cables in a Condut', 'Nos. of cables', 'No. of 6 sq.mm. cross-sectional area cable in 20 mm. dia conduit');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('2.4', 'Maximum number of Cables in a Condut', 'Nos. of cables', 'No. of 2.5 sq.mm. cross-sectional area cable in 25 mm.');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('2.5', 'Maximum number of Cables in a Condut', 'Nos. of cables', 'No. of 4 sq.mm. cross-sectional area cable in 25 mm. dia conduit	');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('2.6', 'Maximum number of Cables in a Condut', 'Nos. of cables', 'No. of 6 sq.mm. cross-sectional area cable in 25 mm. dia conduit');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('2.7', 'Maximum number of Cables in a Condut', 'Nos. of cables', 'No. of 2.5 sq.mm. cross-sectional area cable in 32 mm. dia');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('2.8', 'Maximum number of Cables in a Condut', 'Nos. of cables', 'No. of 4 sq.mm. cross-sectional area cable in 32 mm. dia conduit');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('2.9', 'Maximum number of Cables in a Condut', 'Nos. of cables', 'No. of 6 sq.mm. cross-sectional area cable in 32 mm. dia conduit	');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('3.', 'Earthing', '', '');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('3.1', 'Earthing', '', 'Specified');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('3.2', 'Earthing', '', 'Diameter of rod electrodes of steel or galvanised iron');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('3.3', 'Earthing', '', 'Diameter of rod electrodes of copper');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('3.4', 'Earthing', 'mm.', 'Internal diameter of pipe electrodes of galvanised iron or steel');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('3.5', 'Earthing', 'mm.', 'Internal diameter of pipe electrodes of cast iron');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('3.6', 'Earthing', 'mm.', 'The B17length of the rod & pipe electrodes');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('3.7', 'Earthing', 'mm.', 'Thickness of plate electrodes of galvanised iron or steel');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('3.8', 'Earthing', 'mm.', 'Thickness of plate electrodes of copper');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('3.9', 'Earthing', 'mm.', 'Size of plate electrodes of galvanised iron or steel of copper');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('3.10', 'Earthing', 'mm.', 'Depth of the top edge of plate electrodes buried from ground');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('4.', 'Testing', '', '');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('4.1', 'Testing', '1.5 m.', 'Insulation resistance (Mohm) between earth and the whole system of conductor or any section thereof');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('4.2', 'Testing', '', 'Insulation resistance (Mohm) between the metallic case and all live parts of each rheostat, appliance and sign when they are disconnected.');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('4.3', 'Testing', '', 'Insulation resistance (Mohm) between all the conductors connected to one pole or phase conductor and all the conductor connected to the middle wire or to the neutral or to the other pole of phase conductor');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('4.4', 'Testing', '', 'The applied dc voltage (Volt) of meggering');\n"
              + "INSERT INTO electrical_design_requirement_master (id, group_name, unit, \"data\") "
              + "	VALUES ('4.5', 'Testing', 'Mohm', 'Each switch is placed in phase or neutral ?');\n"
              + "";
    msg.db.delete(sql);

    sql = "INSERT INTO fiscal_year (year_code, end_date, start_date, status, year_name) VALUES (7677, '2020-01-01', '2019-01-01', 'Y', '2076-77');\n"
              + "INSERT INTO fiscal_year (year_code, end_date, start_date, status, year_name) VALUES (7778, '2021-01-01', '2020-01-01', 'N', '2077-78');";
    msg.db.delete(sql);

    sql = "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (1, 'निवेदन', 1.0, 'N', 'N', 'Y', 'Y', '1PAGE', 'N', 'Y', ' /user/forms/map-permit-application-edit', 'building_permit_application', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (2, 'अनुसुची क', 2.0, NULL, NULL, 'Y', NULL, 'AKA', NULL, NULL, '/user/forms/design-approval', 'anusuchi_ka', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (3, 'अनुसुची ख अर्किटेक्चरल B', 3.11, NULL, NULL, 'Y', NULL, 'BAKHA', NULL, NULL, '/user/forms/architecture-design-classB-form', 'architectural_design_b', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (4, 'अनुसुची ख स्ट्रक्चरल B', 3.12, 'Y', 'Y', 'Y', 'Y', 'BSKHA', 'Y', 'Y', '/user/forms/structure-design-classB-form', 'structure_design_b', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (5, 'अनुसुची ख  अर्किटेक्चरल C', 3.21, NULL, NULL, 'Y', NULL, 'CAKHA', NULL, NULL, '/user/forms/architecture-design-classc-form', 'architectural_design_c', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (6, 'अनुसुची ख स्ट्रक्चरल C', 3.22, NULL, NULL, 'Y', NULL, 'CSKHA', NULL, NULL, '/user/forms/structure-design-classc-form', 'structure_design_c', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (7, 'स्यानिटरी डिजाइन', 3.34, NULL, NULL, 'Y', 'Y', 'STD', NULL, 'Y', '/user/forms/sanitary-design', 'sanitary_design', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (8, 'इलेक्ट्रिकल डिजाइन', 3.32, 'N', 'N', 'Y', 'Y', 'ELD', 'N', 'Y', '/user/forms/electrical-design', 'electrical_design', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (9, 'अनुसुची ग', 4.0, 'N', 'N', 'Y', 'Y', 'AGA', 'N', 'Y', '/user/forms/anusuchiga-view', 'anusuchi_ga', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (10, 'अनुसुची घ', 5.0, 'N', 'N', 'Y', 'Y', 'AGHA', 'N', 'Y', '/user/forms/anusuchigha-view', 'anusuchi_gha', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (11, 'नक्सा पास पछि जाँच गरी प्रतिवेदन', 7.0, 'N', 'N', 'N', 'Y', 'NJPP', 'N', 'Y', '/user/forms/map-check-report-view', 'map_check_report', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (12, 'राजस्व विवरण', 8.0, 'N', 'N', 'N', 'Y', 'RJB', 'Y', 'Y', '/user/forms/rajaswo-detail-view', 'rajaswa', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (13, 'संधियारको नाममा जारी भएको सुचना', 12.0, 'N', 'N', 'N', 'Y', 'NNA', 'N', 'Y', '/user/forms/notice-period-for-15-days-view', NULL, 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (14, 'सुचना बुझाएको भर्पाई टास तथा मुचुलका', 13.0, 'N', 'N', 'N', 'Y', 'SBBT', 'N', 'Y', '/user/forms/notice-payment-application-view', 'notice_payment_application', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (15, 'सर्जमिन गरी पेश गर्ने सम्बन्धमा', 14.0, 'Y', 'N', 'N', 'Y', 'SPS', 'N', 'Y', '/user/forms/surjamin-muchulka-view', 'surjamin_muchulka', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (16, 'घर नक्सा सरजमिन मुचुल्का', 16.0, 'Y', 'N', 'N', 'Y', 'GNSM', 'N', 'Y', '/user/forms/gharnaksha-surjamin-muchulka-view', 'gharnaksha_surjamin_muchulka', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (17, 'प्राविधिक प्रतिवेदन', 20.0, 'N', 'N', 'N', 'Y', 'PRAP', 'N', 'Y', '/user/forms/prabhidik-pratibedhan-pesh-view', 'prabhidik_pratibedhan_pesh', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (18, 'संसोधन गरी निवेदन', 21.0, 'N', 'Y', 'Y', 'Y', 'SMNB1', 'N', 'Y', '/user/forms/sansodhan-gari-nibedan', 'sansodhan_gari_nibedan', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (19, 'संसोधन टिप्पणी र आदेश', 22.0, 'N', 'Y', 'N', 'Y', 'STPA', 'N', 'Y', '/user/forms/sansodhan-tippani', 'sansodhan_tippani', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (20, 'प्लिन्थ लेभलसम्म निर्माण निमित्त इजाजत प्रधान गर्ने', 25.0, 'N', 'N', 'N', 'Y', 'PLNTH', 'N', 'Y', '/user/forms/noteorder-pilength-level-view', 'noteorder_pilength_level', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (21, 'प्रथम चरणको अस्थायी निर्माण इजाजत पत्र', 26.0, 'N', 'Y', 'N', 'Y', 'PCIP', 'N', 'Y', '/user/forms/allowance-paper-view', 'allowance_paper', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (22, 'सुपरस्ट्रक्चरको निर्माण कार्यको लागि इजाजतबारे', 27.0, 'N', 'N', 'Y', 'Y', 'SNIPB', 'N', 'Y', '/user/forms/super-structure-build-view', 'super_structure_build', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (23, 'प्लिन्थ लेभलसम्मको निर्माण कार्य सम्पन्नबारे घरधनीको तर्फबाट राखिएको सुपरिवेक्षकको प्रतिवेदन', 28.0, 'N', 'N', 'Y', 'Y', 'PSGPR', 'N', 'Y', '/user/forms/plinthLevel-OwnerRepresentation-view', 'plinth_level_owner_representation', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (24, 'संसोधन विवरण (पहिलो चरण)', 29.0, 'N', 'N', 'Y', 'Y', 'SMNB2', 'N', 'Y', '/user/forms/sansodhan-bibaran-pahilo', 'sansodhan_bibaran_pahilo', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (25, 'संसोधनको टिप्पणी आदेश', 33.0, 'N', 'Y', 'N', 'Y', 'STPA2', 'N', 'Y', '/user/forms/sansodhanko-tippani-adesh', 'sansodhanko_tippani_adesh', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (26, 'सुपरस्ट्रक्चर निर्माणका निमित्त इजाजत प्रदान गर्ने टिप्पणी आदेश', 28.22, 'N', 'Y', 'N', 'Y', 'SNNTP', 'N', 'Y', '/user/forms/superStructure-noteOrder-view', 'super_structure_noteorder', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (27, 'दोस्रो चरणको इजाजत पत्र', 29.11, 'N', 'Y', 'N', 'Y', 'DCIP', 'N', 'Y', '/user/forms/superStructure-construction-view', 'super_structure_construction', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (28, 'निर्माण कार्य सम्पन्‍न प्रमाण पत्र बारे', 301.0, 'N', 'N', 'Y', 'Y', 'NSBN', 'N', 'Y', '/user/forms/dosrocharan-abedan', 'dosrocharan_abedan', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (29, 'सुपरस्ट्रक्चरको निर्माण कार्य सम्पन्‍नबारे घरधनीको तर्फबाट राखिएको सुपरिवेक्षकका प्रतिवेदन', 311.0, 'N', 'N', 'Y', 'Y', 'SNSGR', 'N', 'Y', '/user/forms/dosrocharan-supervisor', 'dosrocharan_supervisor', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (30, 'सुपरस्ट्रक्चरको संसोधन विवरण', 321.0, 'N', 'N', 'Y', 'Y', 'SSSB', 'N', 'Y', '/user/forms/superstructureko-tippaniadesh', 'superstructureko_tippaniadesh', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (31, 'संसोधन/सुपरस्ट्रक्चर इजाजत प्रतिवेदन पेश गरेको बारे', 31.0, 'N', 'Y', 'N', 'Y', 'SIPP', 'N', 'Y', '/user/forms/Samsodhit-Super-structure-Ijajat-Pratibedan', 'samsodhit_super_structure_ijajat_pratibedan', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (32, 'संसोधन सुपरस्ट्रक्चर इजाजत सम्बन्धमा', 35.0, 'N', 'N', 'N', 'Y', 'SSIS', 'N', 'Y', '/user/forms/sansodhan-super-structure-ijjaat', 'sansodhan_super_structure_ijjaat', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (33, 'संसोधन सुपरस्ट्रक्चर टिप्पणी आदेश', 32.0, 'N', 'Y', 'N', 'Y', 'SSTP', 'N', 'Y', '/user/forms/sansodhansuper-tippani-adesh', 'sansodhansuper_tippani_adesh', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (34, 'निर्माण कार्य सम्पन्न प्रमाण-पत्र दिने टिप्पणी आदेश', 37.0, 'N', 'Y', 'N', 'Y', 'NSPT', 'N', 'Y', '/user/forms/certificate-instruction-view', 'certificate_instruction', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (35, 'भवन निर्माण सम्पन्‍न प्रमाण पत्र', 38.0, 'N', 'Y', 'N', 'Y', 'BNPP', 'N', 'Y', '/user/forms/building-finish-certificate-view', NULL, 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (36, 'घर नक्सा नामसारी सम्बन्धमा', 39.0, 'N', 'Y', 'N', 'Y', 'GNNS', 'N', 'Y', '/user/forms/certificate-note', NULL, 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (37, 'नामसारी टिप्पणी आदेश', 40.0, 'N', 'Y', 'N', 'Y', 'NSTA', 'N', 'Y', '/user/forms/namsari-tippani-ades-view', NULL, 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (38, 'नामसारी प्रमाण-पत्र', 41.0, 'N', 'Y', 'N', 'Y', 'NSPP', 'N', 'Y', '/user/forms/building-build-certificate-view', NULL, 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (39, 'नक्सा बनाउने प्रविधिकले गर्नु पर्ने विवरण', 6.0, 'N', 'N', 'Y', 'Y', 'NBPGB', 'N', 'Y', '/user/forms/map-technical-description-view', 'map_technical_description', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (40, 'प्लिन्थ लेभल सम्म निर्माण सम्पन्‍न बारे न.पा. प्राविधिकको राय', 30.0, 'N', 'Y', 'N', 'Y', 'PSNPR', 'N', 'Y', '/user/forms/plinthLevel-techapplication-view', 'plinth_level_tech_application', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (41, 'भवन निर्माण सम्पन्‍न प्रतिवेदन सम्बन्धमा', 36.0, 'N', 'Y', 'N', 'Y', 'BNSP', 'N', 'Y', '/user/forms/dosrocharan-prabidhik-view', 'dosrocharan_prabidhik', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (42, 'माथिको तह मा स्वीकृत को लागि पठाउनु ', 6.1, 'N', 'N', 'N', 'N', 'PPF', 'N', 'N', '/user/forms/forward-to-next', 'null', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (43, 'अमिन सरजमिन', 19.0, 'Y', 'N', 'N', 'Y', 'ADSM', 'N', 'Y', '   /user/forms/gharnaksha-surjamin-muchulka-view', 'gharnaksha_surjamin_muchulka', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (44, 'घर नक्सा कबुलियतमा', 17.0, 'Y', 'N', 'N', 'Y', 'GCWAL', 'N', 'Y', '/user/forms/ghar-compoundwallko-naap', 'ghar_compoundwallko_naap', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (45, 'अमिन कबुलियतमा', 18.0, 'Y', 'N', 'N', 'Y', 'AGNKA', 'N', 'Y', '/user/forms/ghar-naksako-kabuliyatnama', 'ghar_naksako_kabuliyatnama', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) "
              + "	VALUES (46, 'अमिनको स्थलगत निरीक्षण प्रतिवेदन', 42.0, 'Y', 'Y', 'Y', 'Y', 'ASNP', 'Y', 'Y', '/user/forms/aminko-pratibedan', 'aminko_pratibedan', 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (47, 'माथिको तह मा स्वीकृत को लागि पठाउनु Engineer लाई पठाउने', 9.0, 'N', 'N', 'N', 'Y', 'PPF2', 'N', 'Y', NULL, 'null', 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (48, 'राजश्‍व तिर्न राजश्‍व विभागलाई पठाउने', 11.0, 'N', 'N', 'N', 'Y', NULL, 'Y', 'Y', NULL, NULL, 'R');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (49, 'राजस्व विभागले राजश्‍वको भौचर राख्ने', 10.0, 'N', 'N', 'N', 'Y', NULL, 'Y', 'Y', NULL, NULL, 'R');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (50, 'माथिको तह मा स्वीकृत को लागि पठाउनु Engineer लाई पठाउने', 15.0, 'Y', 'N', 'N', 'Y', NULL, 'N', 'Y', NULL, NULL, 'A');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (51, 'संसोधन भएमा  designer लाई पठाउने', 20.1, 'N', 'Y', 'Y', 'Y', NULL, 'N', 'Y', NULL, NULL, 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (52, 'संसोधन विवरण subeng लाई पठाउने', 21.1, 'Y', 'Y', 'Y', 'Y', NULL, 'Y', 'Y', NULL, NULL, 'A');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (53, 'संसोधन विवरण eng लाई पठाउने', 22.1, 'N', 'Y', 'N', 'Y', NULL, 'N', 'Y', NULL, NULL, 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (54, 'संसोधन विवरण Coa लाई पठाउने', 22.2, 'N', 'Y', 'N', 'Y', NULL, 'N', 'N', NULL, NULL, 'A');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by)	VALUES (56, 'संसोधन विवरणको राजश्‍व भौचर upload', 23.0, 'Y', 'Y', 'Y', 'Y', NULL, 'Y', 'Y', NULL, NULL, 'R');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (57, 'संसोधन विवरण  भौचर subeng लाई पठाउने', 23.1, 'Y', 'Y', 'Y', 'Y', NULL, 'Y', 'Y', NULL, NULL, 'R');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (58, 'माथिको तह मा स्वीकृत को लागि पठाउनु Engineer लाई पठाउने', 26.1, 'N', 'Y', 'N', 'Y', NULL, 'N', 'Y', NULL, NULL, 'B');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (59, 'माथिको तह मा स्वीकृत को लागि पठाउनु Coa लाई पठाउने', 26.2, 'Y', 'Y', 'N', 'Y', NULL, 'Y', 'N', NULL, NULL, 'A');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (60, 'माथिको तह मा स्वीकृत को लागि subeng लाई पठाउनु', 29.1, 'Y', 'Y', 'Y', 'Y', NULL, 'Y', 'Y', NULL, NULL, 'D');\n"
              + "INSERT INTO form_name_master (id, \"name\", \"position\", amin_approval, chief_approval, designer_approval, engr_approval, page_code, rajasow_approval, sub_engr_approval, view_url, \"table_name\", enter_by) VALUES (61, 'माथिको तह मा स्वीकृत को लागि पठाउनु Engineer लाई पठाउने', 34.0, 'Y', 'Y', 'Y', 'Y', NULL, 'Y', 'Y', NULL, NULL, 'B');";
    msg.db.save(sql);
    sql = "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (2, 1.0, 1, 1, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (3, 2.0, 2, 1, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (1, 3.1, 3, 1, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (4, 3.2, 4, 1, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (5, 4.1, 5, 1, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (7, 4.3, 8, 1, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (6, 4.2, 6, 1, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (8, 4.4, 7, 1, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (9, 5.0, 9, 1, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (10, 6.0, 10, 1, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (11, 7.0, 39, 1, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (15, 1.0, 1, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (13, 2.0, 2, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (12, 3.0, 3, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (14, 4.0, 3, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (16, 5.0, 5, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (17, 6.0, 6, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (18, 7.0, 8, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (19, 8.0, 7, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (20, 9.0, 9, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (21, 10.0, 10, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (22, 11.0, 39, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (23, 12.0, 11, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (24, 13.0, 12, 10, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (25, 14.0, 42, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (26, 1.0, 1, 8, 'C');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (27, 15.0, 1, 1, 'B');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (28, 7.1, 42, 8, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (29, 8.0, 11, 8, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (30, 9.0, 12, 8, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (31, 10.0, 49, 8, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (32, 11.0, 13, 8, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (34, 13.0, 16, 8, 'D');\n"
              + "INSERT INTO form_group (id, group_position, form_id, group_id, user_type) "
              + "	VALUES (33, 12.0, 15, 8, 'D');";
    msg.db.save(sql);

    sql = "\n"
              + "CREATE OR REPLACE FUNCTION get_bsdate(\n"
              + "	addate character varying)\n"
              + "    RETURNS character varying\n"
              + "    LANGUAGE 'plpgsql'\n"
              + "\n"
              + "    COST 100\n"
              + "    VOLATILE \n"
              + "AS $BODY$\n"
              + "DECLARE bsdate varchar(10);\n"
              + "BEGIN\n"
              + "SELECT bs_date INTO bsdate FROM ad_bs_calender WHERE to_char(ad_date, 'YYYY-MM-DD')=addate;\n"
              + "\n"
              + "RETURN bsdate;\n"
              + "END; $BODY$;\n"
              + "\n"
              + "\n"
              + "CREATE OR REPLACE FUNCTION get_bsdate(\n"
              + "	addate date)\n"
              + "    RETURNS character varying\n"
              + "    LANGUAGE 'plpgsql'\n"
              + "\n"
              + "    COST 100\n"
              + "    VOLATILE \n"
              + "AS $BODY$\n"
              + "DECLARE bsdate varchar(10);\n"
              + "BEGIN\n"
              + "SELECT bs_date INTO bsdate FROM ad_bs_calender WHERE ad_date=addate;\n"
              + "\n"
              + "RETURN bsdate;\n"
              + "END; $BODY$;\n"
              + "\n"
              + "\n"
              + "\n"
              + "CREATE OR REPLACE FUNCTION get_bsdate(\n"
              + "	addate timestamp without time zone)\n"
              + "    RETURNS character varying\n"
              + "    LANGUAGE 'plpgsql'\n"
              + "\n"
              + "    COST 100\n"
              + "    VOLATILE \n"
              + "AS $BODY$\n"
              + "DECLARE bsdate varchar(10);\n"
              + "BEGIN\n"
              + "SELECT bs_date INTO bsdate FROM ad_bs_calender WHERE to_char(ad_date, 'YYYY-MM-DD')=to_char(addate, 'YYYY-MM-DD');\n"
              + "\n"
              + "RETURN bsdate;\n"
              + "END; $BODY$;";
    msg.db.save(sql);
    return msg.respondWithMessage("Success");
}
}
